import streamlit as st

def render():
    st.header("6. Recommendation Output")
    
    if 'final_recommendation' not in st.session_state:
        st.warning("Please run the Agentic Orchestrator in Panel 5 first.")
        return
        
    st.markdown("""
    *Note: The following recommendation is generated by the Agentic Orchestration layer. 
    It is strictly constrained to a fixed rule table based on AHA/ACC guidelines to ensure clinical safety, preventing open-ended hallucination.*
    """)
    
    st.markdown("---")
    
    if 'last_prediction' in st.session_state:
        risk = st.session_state.last_prediction['risk_score']
        risk_class = st.session_state.last_prediction['class']
        
        # Use success/error cards based on risk
        if risk > 50:
            st.error(f"### Current Status: {risk_class} ({risk:.1f}% Risk) 🚨")
        else:
            st.success(f"### Current Status: {risk_class} ({risk:.1f}% Risk) ✅")
        
    st.markdown("### 📋 Orchestrator Recommendation")
    # Display the final recommendation as a clean card
    with st.container(border=True):
        st.info(f"**{st.session_state.final_recommendation}**")
    
    # Display citations
    st.markdown("#### Citations & Grounding")
    
    col1, col2 = st.columns(2)
    
    with col1:
        with st.container(border=True):
            st.markdown("🛡️ **Guideline Rules Triggered:**")
            if st.session_state.cited_rules:
                for rule in st.session_state.cited_rules:
                    st.markdown(f"- 📘 `{rule['rule_id']}`")
            else:
                st.markdown("- *None triggered*")
            
    with col2:
        with st.container(border=True):
            st.markdown("🔬 **Key Risk Drivers (SHAP):**")
            if 'top_shap_features' in st.session_state and st.session_state.top_shap_features:
                for feature in st.session_state.top_shap_features:
                    st.markdown(f"- ⚠️ `{feature}`")
            else:
                st.markdown("- *(Run SHAP explainer first)*")
            
    st.markdown("---")
    st.info("👈 Proceed to **7. Cross-Dataset Comparison** to review model generalization.")
